# Copyright 2022 OpenHW Group
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

# Run all lint checks
name: lint
on: [push, pull_request]

env:
  VERIBLE_VERSION: 0.0-1824-ga3b5bedf

jobs:

  #####################
  # Vendor Up-to-Date #
  #####################
  # Check that all vendored sources are up-to-date.
  check-vendor:
    name: Vendor Up-to-Date
    runs-on: ubuntu-lastest
    container:
      image: luigi2898/x-heep:light
    steps:
    - uses: actions/checkout@v2
    - name: Re-vendor and diff
      run: |
        find . \
            -name '*.vendor.hjson' \
            | xargs -n1 util/vendor.py --verbose \
            && util/git-diff.py --error-msg "::error ::Found differences, please re-vendor."
  ##################
  # MCU Generator  #
  ##################
  mcu_generator:
    name: Generates sv files
    # This job runs on Linux (fixed ubuntu version)
    runs-on: ubuntu-latest
    container:
      image: luigi2898/x-heep:light
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Gen
      run: |
        make mcu-gen
        util/git-diff.py --error-msg "::error ::Found differences in SystemVerilog files generated with default configuration."