name: Simulate all apps
on: [pull_request]

jobs:
  simulate:
    runs-on: ubuntu-latest
    container:
      image: luigi2898/x-heep:light
    name: Simulate all apps. All must pass.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run all apps
        run: |
          conda init bash
          source /root/.bashrc
          conda activate core-v-mini-mcu
          make clean-all
          make mcu-gen MEMORY_BANKS=6
          python3 .github/workflows/sim-apps-job/test-apps.py