name: Simulate all apps
on: [pull_request]

jobs:
  simulate:
    runs-on: ubuntu-latest
    container:
        image: luigi2898/x-heep:light
    name: Simulate all apps. All must pass.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run all apps
        run: |
            ./.github/workflows/build-apps-job/setup-sim.sh  
